export type Category = {
  slug: string
  name: string
  nameEn: string
  desc: string
  longDesc: string
  img: string
  heroImg: string
  count: number
  tags: string[]
}

export type Product = {
  slug: string
  categorySlug: string
  name: string
  code: string
  price: string
  desc: string
  img: string
  images: string[]
  features: string[]
  sizes: string[]
  materials: string[]
  inStock: boolean
  badge?: string
}

export const categories: Category[] = [
  {
    slug: 'hanging',
    name: 'מערכות תלייה',
    nameEn: 'Hanging Systems',
    desc: 'פתרונות תלייה מקצועיים לחנויות ביגוד ואביזרים בכל הגדלים',
    longDesc: 'מגוון רחב של מוטות, זרועות, מתלים ומערכות תלייה מקצועיות שמתאימות לחנויות ביגוד, אופנה, ואביזרים. ניתן להתאמה אישית לכל מרחב.',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1800&q=85',
    count: 24,
    tags: ['ביגוד', 'אופנה', 'אביזרים'],
  },
  {
    slug: 'mannequins',
    name: 'בובות ראווה',
    nameEn: 'Mannequins',
    desc: 'בובות ראווה לכל קו מוצרים וסגנון חנות',
    longDesc: 'אוסף רחב של בובות ראווה מלאות, חצי גוף, ראשים וידיים — לכל סגנון חנות. בסיום בגוון לבן, שחור, עץ וצבעים מותאמים אישית.',
    img: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=1800&q=85',
    count: 18,
    tags: ['ביגוד', 'אופנה', 'ראווה'],
  },
  {
    slug: 'shelving',
    name: 'מידוף לחנויות',
    nameEn: 'Store Shelving',
    desc: 'מדפים מקצועיים לכל שימוש קמעונאי',
    longDesc: 'מדפי קיר, מדפי עמידה, מדפי זכוכית, ומערכות מידוף מודולריות שמתאימות לחנויות מזון, פארמה, ספרים, אלקטרוניקה ועוד.',
    img: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=1800&q=85',
    count: 32,
    tags: ['מזון', 'פארמה', 'ספרים', 'אלקטרוניקה'],
  },
  {
    slug: 'slatwall',
    name: 'קירות מחורצים',
    nameEn: 'Slatwall Systems',
    desc: 'מערכות קיר גמישות שמתאימות לכל פריסה',
    longDesc: 'לוחות סלאטוול MDF ו-PVC בגוונים רבים, עם מגוון רחב של אביזרים: ווים, מדפים, קולבים, ומסגרות זכוכית. הפתרון הגמיש ביותר לתצוגה.',
    img: 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=1800&q=85',
    count: 45,
    tags: ['גמישות', 'מגוון', 'התאמה אישית'],
  },
  {
    slug: 'counters',
    name: 'דלפקים וויטרינות',
    nameEn: 'Counters & Showcases',
    desc: 'דלפקי קופה, שירות ותצוגה בהתאמה אישית',
    longDesc: 'דלפקי קופה, שירות לקוחות, ויטרינות זכוכית מוארות, ושולחנות תצוגה — בהתאמה אישית מלאה לחומרים, מידות, ועיצוב.',
    img: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1800&q=85',
    count: 16,
    tags: ['קופה', 'שירות', 'ויטרינה'],
  },
  {
    slug: 'hangers',
    name: 'קולבים ואביזרים',
    nameEn: 'Hangers & Accessories',
    desc: 'קולבים, ווים ואביזרי תצוגה לכל סוג חנות',
    longDesc: 'קולבי עץ, מתכת ופלסטיק, ווים בגדלים שונים, קליפסים, מחזיקי תגים ועוד — כל האביזרים הקטנים שמשלימים את סביבת התצוגה.',
    img: 'https://images.unsplash.com/photo-1603217039863-aa0c865404f7?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1603217039863-aa0c865404f7?w=1800&q=85',
    count: 120,
    tags: ['אביזרים', 'קולבים', 'ווים'],
  },
  {
    slug: 'stands',
    name: 'סטנדים ומחזיקים',
    nameEn: 'Stands & Holders',
    desc: 'סטנדים עצמאיים, מחזיקי מוצרים ותצוגות פריסה חופשית',
    longDesc: 'סטנדים מסתובבים, מתלי ספרים, מחזיקי צעצועים, תצוגות בקבוקים ועוד — לכל מוצר יש את הסטנד שלו.',
    img: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=900&q=85',
    heroImg: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1800&q=85',
    count: 28,
    tags: ['עצמאי', 'פריסה חופשית', 'מסתובב'],
  },
]

// ─── IMAGES (reused across products for demo) ───────────────────────────────
const IMG = {
  fashion1: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
  fashion2: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&q=80',
  fashion3: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&q=80',
  mannequin1: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
  mannequin2: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80',
  shelf1: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=600&q=80',
  shelf2: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80',
  slatwall1: 'https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=600&q=80',
  counter1: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80',
  counter2: 'https://images.unsplash.com/photo-1527799820374-87591a16f725?w=600&q=80',
  hanger1: 'https://images.unsplash.com/photo-1603217039863-aa0c865404f7?w=600&q=80',
  stand1: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600&q=80',
  cosmetic1: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80',
  pharmacy1: 'https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=600&q=80',
}

export const products: Product[] = [

  // ══════════════════════════════════════════
  // מערכות תלייה — HANGING
  // ══════════════════════════════════════════
  {
    slug: 'double-rail-rack',
    categorySlug: 'hanging',
    name: 'מתלה מוט כפול',
    code: 'HNG-001',
    price: '₪480–₪680',
    desc: 'מתלה דו-מוטי עם מוט עליון ותחתון לניצול מקסימלי של גובה. מתאים לחצאיות, חולצות ומכנסיים.',
    img: IMG.fashion1,
    images: [IMG.fashion1, IMG.fashion2],
    features: ['מוט עליון ותחתון', 'התאמת גובה', 'זרימה חלקה', 'בסיס יציב'],
    sizes: ['60 ס"מ', '90 ס"מ', '120 ס"מ', '150 ס"מ'],
    materials: ['כרום', 'שחור מט', 'לבן'],
    inStock: true,
    badge: 'נמכר ביותר',
  },
  {
    slug: 'wall-arm-straight',
    categorySlug: 'hanging',
    name: 'זרוע קיר ישרה',
    code: 'HNG-002',
    price: '₪95–₪145',
    desc: 'זרוע קיר בסיסית ויציבה להצגת ביגוד בזרם ישר. מתאימה לכל מערכת קיר תואמת.',
    img: IMG.fashion2,
    images: [IMG.fashion2],
    features: ['עומס עד 15 ק"ג', 'נעילה מהירה', 'מתאים לסלאטוול'],
    sizes: ['30 ס"מ', '45 ס"מ', '60 ס"מ'],
    materials: ['כרום', 'שחור מט'],
    inStock: true,
  },
  {
    slug: 't-stand-adjustable',
    categorySlug: 'hanging',
    name: 'T-Stand מתכוונן',
    code: 'HNG-003',
    price: '₪320–₪420',
    desc: 'סטנד T-shape עצמאי עם אפשרות כיוון גובה. אידיאלי לאזורים פתוחים ולפריסה גמישה.',
    img: IMG.fashion1,
    images: [IMG.fashion1],
    features: ['כיוון גובה 140–190 ס"מ', 'בסיס עגול משקולת', 'גלגלות אופציונליות'],
    sizes: ['סטנדרט'],
    materials: ['כרום', 'שחור'],
    inStock: true,
  },
  {
    slug: 'garment-rail-mobile',
    categorySlug: 'hanging',
    name: 'עגלת תלייה ניידת',
    code: 'HNG-004',
    price: '₪580–₪820',
    desc: 'עגלת תלייה ניידת עם מוט כרום וגלגלות בולמות. מתאימה לחדרי הלבשה ולפריסה זמנית.',
    img: IMG.fashion2,
    images: [IMG.fashion2],
    features: ['גלגלות עם בלם', 'מוט ניתן להסרה', 'תא תחתון לתיקים'],
    sizes: ['90 ס"מ', '120 ס"מ'],
    materials: ['כרום'],
    inStock: true,
  },
  {
    slug: 'wall-arm-waterfall',
    categorySlug: 'hanging',
    name: 'זרוע מפל — 5 ווים',
    code: 'HNG-005',
    price: '₪120–₪160',
    desc: 'זרוע קיר בסגנון מפל עם 5 ווים מדורגים. מאפשרת תצוגת פריטים מרובים בשטח מינימלי.',
    img: IMG.fashion1,
    images: [IMG.fashion1],
    features: ['5 ווים מדורגים', 'זווית נוחה לצפייה', 'עומד בעומס 20 ק"ג'],
    sizes: ['45 ס"מ'],
    materials: ['כרום', 'שחור מט'],
    inStock: true,
  },
  {
    slug: 'round-rack-single',
    categorySlug: 'hanging',
    name: 'מתלה עגול — מוט יחיד',
    code: 'HNG-006',
    price: '₪380–₪520',
    desc: 'מתלה עגול עצמאי בקוטר 90 ס"מ. מציג עד 40 פריטי ביגוד וקל להזזה.',
    img: IMG.fashion2,
    images: [IMG.fashion2],
    features: ['קוטר 90 ס"מ', 'גובה מתכוונן', 'גלגלות 360°', 'עד 40 קולבים'],
    sizes: ['קוטר 90 ס"מ'],
    materials: ['כרום'],
    inStock: true,
    badge: 'חדש',
  },
  {
    slug: 'hanging-cube-system',
    categorySlug: 'hanging',
    name: 'מערכת קובייה לתלייה',
    code: 'HNG-007',
    price: '₪1,200–₪1,800',
    desc: 'מערכת קוביות מודולרית עם מוטות תלייה, מדפים ותאים. פתרון all-in-one לחנות ביגוד.',
    img: IMG.fashion3,
    images: [IMG.fashion3, IMG.fashion1],
    features: ['מודולרי', 'מוטות + מדפים + תאים', 'ניתן להרחבה', 'עמידות גבוהה'],
    sizes: ['120×40×180 ס"מ', '180×40×180 ס"מ'],
    materials: ['MDF + מתכת'],
    inStock: true,
  },
  {
    slug: 'display-arm-angled',
    categorySlug: 'hanging',
    name: 'זרוע קיר בזווית 45°',
    code: 'HNG-008',
    price: '₪110–₪155',
    desc: 'זרוע קיר בזווית 45 מעלות שמציגה את הביגוד קדמה. הצגה ברורה ומושכת עיניים.',
    img: IMG.fashion1,
    images: [IMG.fashion1],
    features: ['זווית 45°', 'הצגה קדמית', 'עומד בעומס 12 ק"ג'],
    sizes: ['30 ס"מ', '45 ס"מ'],
    materials: ['כרום', 'שחור', 'לבן'],
    inStock: true,
  },

  // ══════════════════════════════════════════
  // בובות ראווה — MANNEQUINS
  // ══════════════════════════════════════════
  {
    slug: 'abstract-full-body-white',
    categorySlug: 'mannequins',
    name: 'בובה מלאה — אבסטרקט לבן',
    code: 'MAN-001',
    price: '₪680–₪920',
    desc: 'בובת ראווה גוף מלא בסגנון אבסטרקט עם פנים חלקות. מיועדת להדגשת קו הביגוד ללא הסחת דעת.',
    img: IMG.mannequin1,
    images: [IMG.mannequin1],
    features: ['פוזה ניתנת להחלפה', 'בסיס זכוכית', 'ידיים נשלפות', 'עמיד לאורך זמן'],
    sizes: ['S/M', 'L/XL'],
    materials: ['פיברגלס'],
    inStock: true,
    badge: 'נמכר ביותר',
  },
  {
    slug: 'abstract-full-body-black',
    categorySlug: 'mannequins',
    name: 'בובה מלאה — אבסטרקט שחור',
    code: 'MAN-002',
    price: '₪720–₪960',
    desc: 'גרסת השחור של הבובה האבסטרקטית. מבליטה צבעים בהירים ויוצרת ניגוד דרמטי.',
    img: IMG.mannequin2,
    images: [IMG.mannequin2, IMG.mannequin1],
    features: ['גימור שחור מט', 'פוזה ניתנת להחלפה', 'בסיס עגול שחור', 'ידיים נשלפות'],
    sizes: ['S/M', 'L/XL'],
    materials: ['פיברגלס'],
    inStock: true,
  },
  {
    slug: 'child-mannequin-3-6',
    categorySlug: 'mannequins',
    name: 'בובת ילד — גיל 3–6',
    code: 'MAN-003',
    price: '₪420–₪580',
    desc: 'בובת ראווה לילדים בגיל 3–6, בפוזות שובבות ומחייכות. מתאימה לחנויות ביגוד לילדים.',
    img: IMG.mannequin1,
    images: [IMG.mannequin1],
    features: ['פוזות שמחות', 'עמיד לעינויים', 'בסיס יציב'],
    sizes: ['3–4 שנים', '5–6 שנים'],
    materials: ['פלסטיק ABS'],
    inStock: true,
  },
  {
    slug: 'child-mannequin-7-12',
    categorySlug: 'mannequins',
    name: 'בובת ילד — גיל 7–12',
    code: 'MAN-004',
    price: '₪480–₪640',
    desc: 'בובת ראווה לגיל בית ספר. יחס גוף אמיתי, מתאימה לביגוד ספורט ויומיומי.',
    img: IMG.mannequin2,
    images: [IMG.mannequin2],
    features: ['יחס גוף מציאותי', 'בסיס יציב', 'ידיים נשלפות'],
    sizes: ['7–9 שנים', '10–12 שנים'],
    materials: ['פיברגלס'],
    inStock: true,
  },
  {
    slug: 'half-body-torso',
    categorySlug: 'mannequins',
    name: 'חצי גוף — תא עליון',
    code: 'MAN-005',
    price: '₪280–₪380',
    desc: 'בובת חצי גוף לתצוגת חולצות, ז\'קטים ותכשיטים. גמישה וחסכונית יותר מגוף מלא.',
    img: IMG.mannequin1,
    images: [IMG.mannequin1],
    features: ['גמישות פרישה', 'עמוד מסתובב', 'ניתן להנחה על מדף'],
    sizes: ['S', 'M', 'L'],
    materials: ['פיברגלס', 'פוליאוריתן'],
    inStock: true,
  },
  {
    slug: 'headless-mannequin-modern',
    categorySlug: 'mannequins',
    name: 'בובה ללא ראש — מודרני',
    code: 'MAN-006',
    price: '₪560–₪780',
    desc: 'בובה עצמאית ללא ראש בסגנון מודרני ומינימליסטי. שמה את הדגש על הביגוד בלבד.',
    img: IMG.mannequin2,
    images: [IMG.mannequin2],
    features: ['סגנון מינימליסטי', 'פוזה ניטרלית', 'בסיס מרובע שחור'],
    sizes: ['S/M', 'M/L'],
    materials: ['פיברגלס'],
    inStock: true,
    badge: 'חדש',
  },
  {
    slug: 'sitting-mannequin',
    categorySlug: 'mannequins',
    name: 'בובה יושבת',
    code: 'MAN-007',
    price: '₪740–₪1,000',
    desc: 'בובת ראווה בפוזת ישיבה — לתצוגה על ספסלים, וויטרינות נמוכות ואזורי מנוחה.',
    img: IMG.mannequin1,
    images: [IMG.mannequin1],
    features: ['פוזת ישיבה', 'ניתן לשינוי זווית ידיים', 'בסיס מותאם'],
    sizes: ['M'],
    materials: ['פיברגלס'],
    inStock: false,
    badge: 'מלאי מוגבל',
  },
  {
    slug: 'dress-form-adjustable',
    categorySlug: 'mannequins',
    name: 'מחזיק שמלות מתכוונן',
    code: 'MAN-008',
    price: '₪320–₪480',
    desc: 'מחזיק שמלות מקצועי עם גוף מתכוונן. מתאים לסטודיו, לחנות ולחדר מדידה.',
    img: IMG.mannequin2,
    images: [IMG.mannequin2],
    features: ['גוף מתכוונן', 'כיסוי קטיפה', 'כיוון גובה', 'גלגלות'],
    sizes: ['S', 'M', 'L', 'XL'],
    materials: ['מתכת + ספוג + קטיפה'],
    inStock: true,
  },

  // ══════════════════════════════════════════
  // מידוף — SHELVING
  // ══════════════════════════════════════════
  {
    slug: 'wall-shelf-bracket-set',
    categorySlug: 'shelving',
    name: 'מדף קיר עם זרועות — סט',
    code: 'SHV-001',
    price: '₪180–₪260',
    desc: 'מדף MDF עם זרועות מתכת. בא בסטים של 2–4 מדפים. מתאים לכל סוג חנות.',
    img: IMG.shelf1,
    images: [IMG.shelf1],
    features: ['עומס עד 25 ק"ג', 'גוון לפי בחירה', 'הרכבה פשוטה'],
    sizes: ['60 ס"מ', '90 ס"מ', '120 ס"מ'],
    materials: ['MDF + מתכת', 'עץ מלא + מתכת'],
    inStock: true,
    badge: 'חדש',
  },
  {
    slug: 'gondola-shelving-unit',
    categorySlug: 'shelving',
    name: 'גונדולה קמעונאית',
    code: 'SHV-002',
    price: '₪1,200–₪2,800',
    desc: 'מדפי גונדולה דו-צדדיים לפריסה בתוך חנות. גובה ומרחק בין המדפים מתכווננים.',
    img: IMG.shelf1,
    images: [IMG.shelf1],
    features: ['כיוון גובה מדפים', 'דו-צדדי', 'יחידות הרחבה', '180 ס"מ גובה'],
    sizes: ['90×45 ס"מ', '120×45 ס"מ'],
    materials: ['מתכת + MDF'],
    inStock: true,
  },
  {
    slug: 'glass-shelf-system',
    categorySlug: 'shelving',
    name: 'מערכת מדפי זכוכית',
    code: 'SHV-003',
    price: '₪550–₪1,100',
    desc: 'מדפי זכוכית טמפרד על פסי אלומיניום. מתאים לתצוגת מוצרים פרימיום, תכשיטים וקוסמטיקה.',
    img: IMG.shelf2,
    images: [IMG.shelf2, IMG.shelf1],
    features: ['זכוכית טמפרד 8 מ"מ', 'פסי אלומיניום', 'כיוון גובה', 'תאורה אופציונלית'],
    sizes: ['60 ס"מ', '90 ס"מ', '120 ס"מ'],
    materials: ['זכוכית + אלומיניום'],
    inStock: true,
    badge: 'פרימיום',
  },
  {
    slug: 'pharmacy-shelving-set',
    categorySlug: 'shelving',
    name: 'מדפי פארמה — סט מלא',
    code: 'SHV-004',
    price: '₪2,400–₪4,800',
    desc: 'מערכת מדפים ייעודית לבתי מרקחת ופארמה. חלק קדמי פרסום, חלק אחורי אחסון.',
    img: IMG.pharmacy1,
    images: [IMG.pharmacy1, IMG.shelf1],
    features: ['חלק קדמי + אחסון אחורי', 'שילוט משולב', 'תאורת LED', 'גובה 180 ס"מ'],
    sizes: ['90 ס"מ', '120 ס"מ'],
    materials: ['MDF לבן + מתכת'],
    inStock: true,
  },
  {
    slug: 'floating-shelf-single',
    categorySlug: 'shelving',
    name: 'מדף צף — יחיד',
    code: 'SHV-005',
    price: '₪95–₪155',
    desc: 'מדף צף נקי וצנוע, ללא זרועות גלויות. מעניק מראה מינימליסטי לכל קיר.',
    img: IMG.shelf2,
    images: [IMG.shelf2],
    features: ['ללא זרועות גלויות', 'קיבוע נסתר', 'עומד בעומס 15 ק"ג'],
    sizes: ['60 ס"מ', '80 ס"מ', '100 ס"מ', '120 ס"מ'],
    materials: ['MDF', 'עץ אגוז', 'עץ אלון'],
    inStock: true,
  },
  {
    slug: 'wire-grid-shelf',
    categorySlug: 'shelving',
    name: 'מדף רשת תיל',
    code: 'SHV-006',
    price: '₪140–₪200',
    desc: 'מדף תיל מרחיק רושם לחנויות ירקות, תוצרת טבעית ואורגנית. מאוורר ונקי.',
    img: IMG.shelf1,
    images: [IMG.shelf1],
    features: ['מאוורר', 'עמיד בלחות', 'ניתן להשחלה בכל גובה'],
    sizes: ['60 ס"מ', '90 ס"מ'],
    materials: ['תיל מצופה כרום', 'תיל שחור אפוקסי'],
    inStock: true,
  },
  {
    slug: 'corner-shelf-unit',
    categorySlug: 'shelving',
    name: 'יחידת מדפי פינה',
    code: 'SHV-007',
    price: '₪680–₪980',
    desc: 'פתרון חכם לפינות חנות — יחידת מדפים בזווית 90° שממצה כל שטח.',
    img: IMG.shelf2,
    images: [IMG.shelf2],
    features: ['מנצל פינות', 'כיוון גובה מדפים', '5 מדפים כלולים'],
    sizes: ['45×45×180 ס"מ'],
    materials: ['MDF + מתכת'],
    inStock: true,
  },

  // ══════════════════════════════════════════
  // קירות מחורצים — SLATWALL
  // ══════════════════════════════════════════
  {
    slug: 'slatwall-mdf-white',
    categorySlug: 'slatwall',
    name: 'לוח סלאטוול MDF לבן',
    code: 'SLW-001',
    price: '₪145–₪195',
    desc: 'לוח סלאטוול MDF בגוון לבן, מוכן להתקנה. חריצים ברוחב 7.5 ס"מ, מרווח 10 ס"מ.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['MDF E1', 'צבע עמיד', 'תואם לכל אביזרי סלאטוול'],
    sizes: ['120×60 ס"מ', '240×120 ס"מ'],
    materials: ['MDF'],
    inStock: true,
  },
  {
    slug: 'slatwall-mdf-black',
    categorySlug: 'slatwall',
    name: 'לוח סלאטוול MDF שחור',
    code: 'SLW-002',
    price: '₪155–₪210',
    desc: 'לוח סלאטוול MDF בגוון שחור מט. מעניק לחנות מראה פרמיום ודרמטי.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['MDF E1', 'גוון שחור מט', 'תואם לכל אביזרי סלאטוול'],
    sizes: ['120×60 ס"מ', '240×120 ס"מ'],
    materials: ['MDF'],
    inStock: true,
  },
  {
    slug: 'slatwall-pvc-panel',
    categorySlug: 'slatwall',
    name: 'לוח סלאטוול PVC — עמיד לחות',
    code: 'SLW-003',
    price: '₪195–₪260',
    desc: 'לוח סלאטוול PVC עמיד בפני לחות, לחנויות מזון, פירות וירקות וסביבות רטובות.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['עמיד לחות 100%', 'ניתן לשטיפה', 'עמיד בטמפרטורות קיצוניות'],
    sizes: ['120×60 ס"מ', '240×120 ס"מ'],
    materials: ['PVC'],
    inStock: true,
    badge: 'מיוחד',
  },
  {
    slug: 'slatwall-hook-set',
    categorySlug: 'slatwall',
    name: 'סט ווים לסלאטוול — 10 יח\'',
    code: 'SLW-004',
    price: '₪85–₪130',
    desc: 'סט 10 ווים לסלאטוול בגדלים שונים. מתאים לתצוגת מוצרים קטנים ואביזרים.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['כרום מבריק', 'עומס 2 ק"ג לווו', 'התקנה מהירה'],
    sizes: ['10 ס"מ', '15 ס"מ', '20 ס"מ'],
    materials: ['מתכת כרום'],
    inStock: true,
    badge: 'ערך מצוין',
  },
  {
    slug: 'slatwall-shelf-bracket',
    categorySlug: 'slatwall',
    name: 'מדף לסלאטוול + זרוע',
    code: 'SLW-005',
    price: '₪110–₪175',
    desc: 'מדף MDF עם זרוע מיוחדת לסלאטוול. מסתנכרן מיד לכל לוח, ללא כלים.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['התקנה ללא כלים', 'מדף MDF כלול', 'עומד בעומס 15 ק"ג'],
    sizes: ['30 ס"מ', '45 ס"מ', '60 ס"מ'],
    materials: ['MDF + מתכת'],
    inStock: true,
  },
  {
    slug: 'slatwall-hanger-arm',
    categorySlug: 'slatwall',
    name: 'זרוע תלייה לסלאטוול',
    code: 'SLW-006',
    price: '₪65–₪95',
    desc: 'זרוע תלייה ייעודית לסלאטוול. מאפשרת תצוגת ביגוד ישירות על הקיר המחורץ.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['מתאים לכל סלאטוול', 'ניתן לשינוי מיקום', 'עומד בעומס 12 ק"ג'],
    sizes: ['30 ס"מ', '40 ס"מ'],
    materials: ['כרום', 'שחור'],
    inStock: true,
  },
  {
    slug: 'slatwall-glass-shelf',
    categorySlug: 'slatwall',
    name: 'מדף זכוכית לסלאטוול',
    code: 'SLW-007',
    price: '₪180–₪240',
    desc: 'מדף זכוכית טמפרד עם מסגרת כרום לסלאטוול. לתצוגת קוסמטיקה, תכשיטים ואביזרים.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['זכוכית טמפרד 6 מ"מ', 'מסגרת כרום', 'עומד בעומס 10 ק"ג'],
    sizes: ['30×20 ס"מ', '45×20 ס"מ'],
    materials: ['זכוכית + כרום'],
    inStock: true,
    badge: 'פרימיום',
  },
  {
    slug: 'slatwall-acrylic-tray',
    categorySlug: 'slatwall',
    name: 'מגש אקריל לסלאטוול',
    code: 'SLW-008',
    price: '₪75–₪120',
    desc: 'מגש אקריל שקוף לסלאטוול. מאפשר תצוגת מוצרים קטנים, טבעות, עגילים ואביזרים.',
    img: IMG.slatwall1,
    images: [IMG.slatwall1],
    features: ['אקריל שקוף 3 מ"מ', 'ניתן לניקוי', 'קל משקל'],
    sizes: ['20×15 ס"מ', '30×20 ס"מ'],
    materials: ['אקריל'],
    inStock: true,
  },

  // ══════════════════════════════════════════
  // דלפקים וויטרינות — COUNTERS
  // ══════════════════════════════════════════
  {
    slug: 'glass-showcase-illuminated',
    categorySlug: 'counters',
    name: 'ויטרינת זכוכית מוארת',
    code: 'CNT-001',
    price: '₪2,800–₪4,200',
    desc: 'ויטרינת תצוגה עם תאורת LED פנימית. מתאימה לתכשיטים, שעונים, קוסמטיקה ומוצרי יוקרה.',
    img: IMG.counter1,
    images: [IMG.counter1],
    features: ['תאורת LED 3000K', 'זכוכית טמפרד 6 מ"מ', 'נעילה עם מפתח', 'בסיס MDF'],
    sizes: ['60×45×100 ס"מ', '90×45×100 ס"מ', '120×45×100 ס"מ'],
    materials: ['זכוכית + MDF + מתכת'],
    inStock: true,
    badge: 'פרימיום',
  },
  {
    slug: 'checkout-counter-straight',
    categorySlug: 'counters',
    name: 'דלפק קופה ישר',
    code: 'CNT-002',
    price: '₪2,200–₪4,000',
    desc: 'דלפק קופה ישר עם מגירות ומדפים פנימיים. עיצוב נקי, מתאים לכל סגנון חנות.',
    img: IMG.counter1,
    images: [IMG.counter1],
    features: ['מגירות מסגרת רכה', 'פרופיל אלומיניום', 'ויטרינה אופציונלית'],
    sizes: ['90 ס"מ', '120 ס"מ', '150 ס"מ'],
    materials: ['MDF + למינט'],
    inStock: true,
  },
  {
    slug: 'checkout-counter-l-shape',
    categorySlug: 'counters',
    name: 'דלפק קופה L-Shape',
    code: 'CNT-003',
    price: '₪3,500–₪6,000',
    desc: 'דלפק קופה בפורמט L עם מגירות ומדפים פנימיים. מתאים לחנויות עם שטח קופה גדול.',
    img: IMG.counter1,
    images: [IMG.counter1],
    features: ['מגירות מסגרת רכה', 'כבלים חבויים', 'ויטרינה אופציונלית'],
    sizes: ['מותאם אישית'],
    materials: ['MDF + למינט', 'עץ טבעי'],
    inStock: true,
  },
  {
    slug: 'cosmetic-display-counter',
    categorySlug: 'counters',
    name: 'דלפק תצוגה לקוסמטיקה',
    code: 'CNT-004',
    price: '₪3,200–₪5,500',
    desc: 'דלפק ייעודי לחנויות קוסמטיקה עם משטח בדיקה, ויטרינה ותאורת LED.',
    img: IMG.cosmetic1,
    images: [IMG.cosmetic1, IMG.counter1],
    features: ['משטח בדיקה', 'תאורה ייעודית', 'ויטרינה', 'מראה מובנה'],
    sizes: ['120 ס"מ', '150 ס"מ', '180 ס"מ'],
    materials: ['MDF לבן + זכוכית'],
    inStock: true,
    badge: 'חדש',
  },
  {
    slug: 'low-display-table',
    categorySlug: 'counters',
    name: 'שולחן תצוגה נמוך',
    code: 'CNT-005',
    price: '₪980–₪1,600',
    desc: 'שולחן תצוגה נמוך ועצמאי. ניתן לשימוש כנקודת מיקוד באמצע חנות או בכניסה.',
    img: IMG.counter2,
    images: [IMG.counter2],
    features: ['גובה 70 ס"מ', 'עמיד', 'ניתן לחיבור יחידות נוספות'],
    sizes: ['60×60 ס"מ', '90×60 ס"מ', '120×60 ס"מ'],
    materials: ['MDF', 'עץ מלא', 'זכוכית'],
    inStock: true,
  },
  {
    slug: 'wall-mounted-showcase',
    categorySlug: 'counters',
    name: 'ויטרינת קיר — תלויה',
    code: 'CNT-006',
    price: '₪1,800–₪3,200',
    desc: 'ויטרינת קיר תלויה עם תאורה. חוסכת שטח רצפה ומציגה מוצרים בגובה עיניים.',
    img: IMG.counter1,
    images: [IMG.counter1],
    features: ['תאורת LED', 'נעילה', 'גובה עיניים', 'פריסה מרבית'],
    sizes: ['60×20×40 ס"מ', '90×20×40 ס"מ'],
    materials: ['זכוכית + אלומיניום'],
    inStock: true,
  },

  // ══════════════════════════════════════════
  // קולבים ואביזרים — HANGERS
  // ══════════════════════════════════════════
  {
    slug: 'wooden-hanger-premium',
    categorySlug: 'hangers',
    name: 'קולב עץ פרימיום',
    code: 'HGR-001',
    price: '₪12–₪22',
    desc: 'קולב עץ טבעי עם ציפוי לכה. מוסיף נגיעת יוקרה לחנות ועמיד לשנים.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['עץ אגוז', 'וו מסתובב', 'שכמיות מרופדות אופציונליות'],
    sizes: ['45 ס"מ'],
    materials: ['עץ טבעי', 'עץ צבוע'],
    inStock: true,
    badge: 'יוקרה',
  },
  {
    slug: 'velvet-hanger-pack50',
    categorySlug: 'hangers',
    name: 'קולב קטיפה — אריזת 50',
    code: 'HGR-002',
    price: '₪95–₪130',
    desc: 'קולב קטיפה דק במיוחד, מונע החלקה. באריזה של 50 יח\' בגוונים שונים.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['עובי 5 מ"מ', 'כל הגוונים', 'מונע החלקה'],
    sizes: ['42 ס"מ', '45 ס"מ'],
    materials: ['קטיפה + פלסטיק ABS'],
    inStock: true,
    badge: 'ערך מצוין',
  },
  {
    slug: 'plastic-hanger-pack100',
    categorySlug: 'hangers',
    name: 'קולב פלסטיק — אריזת 100',
    code: 'HGR-003',
    price: '₪65–₪85',
    desc: 'קולב פלסטיק בסיסי לשימוש יומיומי. עמיד, קל ויבוא בכמויות גדולות.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['קל משקל', 'עמיד', 'וו מסתובב'],
    sizes: ['42 ס"מ'],
    materials: ['פלסטיק PP'],
    inStock: true,
  },
  {
    slug: 'pant-hanger-clip',
    categorySlug: 'hangers',
    name: 'קולב מכנסיים — קליפסים',
    code: 'HGR-004',
    price: '₪8–₪14',
    desc: 'קולב מכנסיים עם שני קליפסים. מחזיק בצורה מאובטחת ומונע קמטים.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['קליפסים חזקים', 'פנים מרופד', 'מנגנון נגד החלקה'],
    sizes: ['35 ס"מ'],
    materials: ['מתכת + פלסטיק ABS'],
    inStock: true,
  },
  {
    slug: 'scarf-hanger-ring',
    categorySlug: 'hangers',
    name: 'קולב צעיפים — טבעות',
    code: 'HGR-005',
    price: '₪18–₪28',
    desc: 'קולב לצעיפים, חגורות ואביזרים עם 12 טבעות. מציג עד 12 פריטים על קולב אחד.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['12 טבעות', 'סיבוב 360°', 'וו מסתובב'],
    sizes: ['40 ס"מ'],
    materials: ['מתכת כרום', 'מתכת שחורה'],
    inStock: true,
  },
  {
    slug: 'price-tag-holder',
    categorySlug: 'hangers',
    name: 'מחזיק תגי מחיר',
    code: 'HGR-006',
    price: '₪35–₪55',
    desc: 'מחזיק מקצועי לתגי מחיר — ניתן לקיבוע על מוט, מדף, או קולב.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['מתאים לכל משטח', 'ניתן לסיבוב', 'חבילה של 10'],
    sizes: ['סטנדרט'],
    materials: ['פלסטיק שקוף'],
    inStock: true,
  },
  {
    slug: 'display-hook-s-shape',
    categorySlug: 'hangers',
    name: 'וו S — חבילת 20',
    code: 'HGR-007',
    price: '₪25–₪40',
    desc: 'וו S בסיסי לתלייה על מוטות, רשתות וסלאטוול. חבילה של 20 יחידות.',
    img: IMG.hanger1,
    images: [IMG.hanger1],
    features: ['מתאים לכל משטח', 'עומד בעומס 5 ק"ג', 'חבילה של 20'],
    sizes: ['5 ס"מ', '8 ס"מ', '10 ס"מ'],
    materials: ['מתכת כרום', 'מתכת שחורה'],
    inStock: true,
  },

  // ══════════════════════════════════════════
  // סטנדים ומחזיקים — STANDS
  // ══════════════════════════════════════════
  {
    slug: 'rotating-display-stand',
    categorySlug: 'stands',
    name: 'סטנד מסתובב 360°',
    code: 'STD-001',
    price: '₪280–₪420',
    desc: 'סטנד מסתובב 360 מעלות לתצוגת מפתחות, תכשיטים, ספרים קטנים ועוד.',
    img: IMG.stand1,
    images: [IMG.stand1],
    features: ['סיבוב חלק', 'עומס 8 ק"ג', 'גבהים שונים'],
    sizes: ['30 ס"מ', '40 ס"מ', '50 ס"מ'],
    materials: ['מתכת + אקריל'],
    inStock: true,
  },
  {
    slug: 'floor-stand-poster',
    categorySlug: 'stands',
    name: 'סטנד רצפה לפוסטר A1',
    code: 'STD-002',
    price: '₪180–₪260',
    desc: 'סטנד רצפתי לפוסטרים ושלטים בגודל A1. ניתן לכיוון גובה. מתאים לכניסה לחנות.',
    img: IMG.stand1,
    images: [IMG.stand1],
    features: ['מתאים לA1/A2', 'כיוון גובה', 'קל להזזה'],
    sizes: ['A1', 'A2'],
    materials: ['אלומיניום', 'מתכת שחורה'],
    inStock: true,
  },
  {
    slug: 'book-display-stand',
    categorySlug: 'stands',
    name: 'סטנד תצוגת ספרים',
    code: 'STD-003',
    price: '₪240–₪380',
    desc: 'סטנד עצמאי לתצוגת ספרים, מגזינים וקטלוגים. 6 תאים, מסתובב 360°.',
    img: IMG.stand1,
    images: [IMG.stand1],
    features: ['6 תאים', 'מסתובב 360°', 'עמיד', 'קל להזזה'],
    sizes: ['40×40×150 ס"מ'],
    materials: ['מתכת + MDF'],
    inStock: true,
  },
  {
    slug: 'basket-wire-stand',
    categorySlug: 'stands',
    name: 'סטנד סלסלת תיל',
    code: 'STD-004',
    price: '₪160–₪220',
    desc: 'סטנד עם 3 סלסלות תיל לתצוגת מוצרים קטנים, ממתקים, גרביים וסוורים.',
    img: IMG.stand1,
    images: [IMG.stand1],
    features: ['3 סלסלות', 'תיל כרום', 'ניתן להורדת סלסלות'],
    sizes: ['40×30×120 ס"מ'],
    materials: ['תיל כרום'],
    inStock: true,
    badge: 'ערך מצוין',
  },
  {
    slug: 'shoe-display-stand',
    categorySlug: 'stands',
    name: 'סטנד תצוגת נעליים',
    code: 'STD-005',
    price: '₪320–₪480',
    desc: 'סטנד מדורג לתצוגת נעליים — 4 רמות, מציג עד 8 זוגות. מתאים לחנות נעליים ואופנה.',
    img: IMG.stand1,
    images: [IMG.stand1],
    features: ['4 רמות מדורגות', 'עד 8 זוגות', 'כיוון גובה מדפים'],
    sizes: ['60×30×120 ס"מ'],
    materials: ['MDF + מתכת כרום'],
    inStock: true,
  },
  {
    slug: 'jewelry-display-stand',
    categorySlug: 'stands',
    name: 'סטנד תצוגת תכשיטים',
    code: 'STD-006',
    price: '₪180–₪320',
    desc: 'סטנד קטן לתצוגת תכשיטים — שרשראות, צמידים ועגילים. מתאים לדלפק קופה.',
    img: IMG.counter2,
    images: [IMG.counter2],
    features: ['מתאים לדלפק', 'מסתובב', 'ווים ומדפים', 'קל ונייד'],
    sizes: ['20×20×35 ס"מ'],
    materials: ['אקריל + מתכת'],
    inStock: true,
  },
  {
    slug: 'clothing-table-display',
    categorySlug: 'stands',
    name: 'שולחן תצוגה מקופל',
    code: 'STD-007',
    price: '₪420–₪580',
    desc: 'שולחן תצוגה מקופל לחנות ביגוד. מציג בגדים מקופלים בגובה הנכון לגלישה.',
    img: IMG.fashion2,
    images: [IMG.fashion2],
    features: ['ניתן לקיפול', 'גובה 80 ס"מ', 'משטח 60×90 ס"מ'],
    sizes: ['60×90×80 ס"מ'],
    materials: ['MDF + מתכת'],
    inStock: true,
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find(c => c.slug === slug)
}

export function getProductsByCategory(slug: string): Product[] {
  return products.filter(p => p.categorySlug === slug)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}
